# fly.toml app configuration file generated for week10 on 2023-08-26T05:28:25+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "week10"
primary_region = "sin"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
